export const GStyles = {
  primaryBlue: '#3AAFFF',
  primaryOrange: '#FF8811',
  primaryYellow: '#FDDF50',
  primaryPurple: '#A55FEF',
  white: '#ffff',
  textColor: {
    '#3D3D3D': '#3D3D3D',
  },
  borderColor: {
    '#ECECEC': '#ECECEC',
  },
  blue: {
    light: '#ebf7ff',
    lightHover: '#e1f3ff',
    lightActive: '#c2e6ff',
    normal: '#3aafff',
    normalHover: '#349ee6',
  },
  gray: {
    light: '#ececec',
    lightHover: '#e2e2e2',
    lightActive: '#c3c3c3',
    normal: '#3d3d3d',
    normalHover: '#373737',
    normalActive: '#313131',
    dark: '#2e2e2e',
    darkHover: '#252525',
    darkActive: '#151515',
  },

  SuezOne: 'SuezOne-Regular',
  RussoOne: 'RussoOne-Regular',
  ProstoOneRegular: 'ProstoOne-Regular',
  Poppins: 'Poppins-Regular',
  PoppinsBold: 'Poppins-Bold',
  PoppinsSemiBold: 'Poppins-SemiBold',
  PoppinsMedium: 'Poppins-Medium',
  PoppinsLight: 'Poppins-Light',
  PoppinsExtraLight: 'Poppins-ExtraLight',
};
